OUT
## Observations
Tue Jan  8 21:13:44 PST 2013

## stick

* stick runs appear to be ok


## pump


## downloaded:0

```
```

howdy! pump runs were NOT OK

### Last send command

```
DEBUG:stick:<Stick:status:<LinkStatus:0x03:error:LinkStatus:error:True:reason::size(0)>:command:<TransmitPacket:ReadPumpModel>>:STARTING POLL PHASE:attempt:0
DEBUG:stick:<Stick:status:<LinkStatus:0x03:error:LinkStatus:error:True:reason::size(0)>:command:<TransmitPacket:ReadPumpModel>>:poll:attempt:0
DEBUG:stick:read_status
INFO:stick:link Stick:status:<LinkStatus:0x03:error:LinkStatus:error:True:reason::size(0)>:command:<LinkStatus:0x03:error::size(64)> processing LinkStatus:0x03:error:)
```
### stats before traceback

```
204:INFO:__main__:finished processing UsbStats:0x05 0x01, {'errors.timeouts': 0, 'packets.transmit': 78L, 'errors.naks': 0, 'errors.sequence': 0, 'packets.received': 78L, 'errors.crc': 0}
222:INFO:__main__:finished processing RadioStats:0x05 0x00, {'errors.timeouts': 4, 'packets.transmit': 8L, 'errors.naks': 0, 'errors.sequence': 0, 'packets.received': 1L, 'errors.crc': 0}
223:INFO:__main__:{'radio': {'errors.crc': 0,
224:           'errors.naks': 0,
225:           'errors.sequence': 0,
226:           'errors.timeouts': 4,
227:           'packets.received': 1L,
228:           'packets.transmit': 8L},
229: 'usb': {'errors.crc': 0,
230:         'errors.naks': 0,
231:         'errors.sequence': 0,
232:         'errors.timeouts': 0,
233:         'packets.received': 78L,
234:         'packets.transmit': 78L}}
253:INFO:__main__:finished processing UsbStats:0x05 0x01, {'errors.timeouts': 0, 'packets.transmit': 80L, 'errors.naks': 0, 'errors.sequence': 0, 'packets.received': 80L, 'errors.crc': 0}
271:INFO:__main__:finished processing RadioStats:0x05 0x00, {'errors.timeouts': 4, 'packets.transmit': 8L, 'errors.naks': 0, 'errors.sequence': 0, 'packets.received': 1L, 'errors.crc': 0}
273:{'radio': {'errors.crc': 0,
274:           'errors.naks': 0,
275:           'errors.sequence': 0,
276:           'errors.timeouts': 4,
```
### Traceback

```
0028   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0030   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
0038   0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00    ........
INFO:stick:quit send_force_read, found len: 64 expected 64 after 0 attempts
INFO:stick:LinkStatus:0x03:error:LinkStatus:error:True:reason:

INFO:stick:finished processing LinkStatus:0x03:error:LinkStatus:error:True:reason:, 0
DEBUG:stick:sleeping in POLL, .100
INFO:stick:STOP POLL after 4 attempts:size:0
INFO:stick:download(attempts[1],expect[0],results[0]:data[0]):DONE
Traceback (most recent call last):
  File "pump/commands.py", line 556, in <module>
    do_commands(session)
  File "pump/commands.py", line 455, in do_commands
    log.info('comm:%s:data:%s' % (comm, getattr(comm.getData( ), 'data', None)))
  File "pump/commands.py", line 447, in getData
    length = data[0]
IndexError: bytearray index out of range
Command exited with non-zero status 1
python pump/commands.py /dev/ttyUSB0 208850
	elapsed 0:10.59
	user 0.17
	system 0.07
	CPU 2% (0text+0data 61184max)k
Was there an ACK ERROR?
### DIAGNOSE CRC
```
* NO CRC ERROR FOUND
* NO NAK FOUND
* NOT A CLEAN RUN
