INFO:__main__:howdy! I'm going to take a look at your carelink usb stick.
Traceback (most recent call last):
  File "decocare/stick.py", line 854, in <module>
    stick = Stick(link.Link(port))
  File "/home/sharon/decoding-carelink/decocare/link.py", line 18, in __init__
    self.open( port )
  File "/home/sharon/decoding-carelink/decocare/link.py", line 27, in open
    self.serial = serial.Serial( self.port, **kwds )
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 260, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 276, in open
    raise SerialException("could not open port %s: %s" % (self._port, msg))
serial.serialutil.SerialException: could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Command exited with non-zero status 1
python decocare/stick.py /dev/ttyUSB0
	elapsed 0:00.11
	user 0.08
	system 0.03
	CPU 97% (0text+0data 59312max)k
